version: '3.8'

services:
  # Сервис бекенда для продакшена
  api:
    build:
      context: .
      dockerfile: Dockerfile.prod
    container_name: screen-config-api
    restart: unless-stopped
    env_file: .env
    ports:
      - '5000:5000'
    volumes:
      - .:/app
      - /app/node_modules
    depends_on:
      - mongodb
    networks:
      - app-network
    environment:
      - NODE_ENV=production

  # Сервис MongoDB
  mongodb:
    image: mongo:6
    container_name: mongodb
    restart: unless-stopped
    environment:
      - MONGO_INITDB_DATABASE=screen-config
      - MONGO_INITDB_ROOT_USERNAME=root
      - MONGO_INITDB_ROOT_PASSWORD=rootpassword
    volumes:
      - mongodb-data:/data/db
      - ./mongo-init:/docker-entrypoint-initdb.d
    networks:
      - app-network
    # Продакшен-контейнер не открывает порт для внешнего доступа
    # Доступ к базе осуществляется только через сеть контейнеров

  # Сервис для управления MongoDB (опционально)
  mongo-express:
    image: mongo-express
    container_name: mongo-express
    restart: unless-stopped
    ports:
      - '8081:8081'
    environment:
      - ME_CONFIG_MONGODB_SERVER=mongodb
      - ME_CONFIG_MONGODB_PORT=27017
      - ME_CONFIG_MONGODB_ADMINUSERNAME=root
      - ME_CONFIG_MONGODB_ADMINPASSWORD=rootpassword
      - ME_CONFIG_BASICAUTH_USERNAME=admin
      - ME_CONFIG_BASICAUTH_PASSWORD=password
    depends_on:
      - mongodb
    networks:
      - app-network

volumes:
  mongodb-data:
    driver: local

networks:
  app-network:
    driver: bridge
